# Generated by Django 5.1.1 on 2024-09-26 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_hours', models.IntegerField()),
                ('job_skills', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('job_date', models.CharField(default='', max_length=100)),
                ('job_location', models.CharField(default='', max_length=100)),
                ('job_capacity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConnXt.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_grade', models.IntegerField()),
                ('student_email', models.EmailField(max_length=100)),
                ('student_skills', models.CharField(max_length=200)),
                ('student_experience', models.CharField(max_length=200)),
                ('student_info', models.CharField(max_length=200)),
                ('student_resume', models.CharField(max_length=200)),
                ('profile_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='students_applied',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', through='ConnXt.JobApplication', to='ConnXt.studentinfo'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConnXt.studentinfo'),
        ),
    ]
