# Generated by Django 5.1 on 2024-09-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_hours', models.IntegerField()),
                ('job_skills', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_grade', models.IntegerField()),
                ('student_email', models.EmailField(max_length=100)),
                ('student_skills', models.CharField(max_length=200)),
                ('student_experience', models.CharField(max_length=200)),
                ('student_info', models.CharField(max_length=200)),
            ],
        ),
    ]
