# Generated by Django 5.1.1 on 2024-09-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnXt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_date',
            field=models.CharField(default='01/01/2024', max_length=100),
        ),
    ]
