# Generated by Django 5.1.1 on 2024-09-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnXt', '0002_jobposting_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
