# Generated by Django 5.1.1 on 2024-09-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnXt', '0004_jobposting_job_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
