# Generated by Django 5.1.1 on 2024-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnXt', '0006_alter_jobposting_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_resume',
            field=models.CharField(default='', max_length=200),
        ),
    ]
