# Generated by Django 5.1.1 on 2024-09-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnXt', '0008_alter_studentinfo_student_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_resume',
            field=models.CharField(max_length=200),
        ),
    ]
